# Generated by Django 4.0.4 on 2022-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensemodel_cost_incomemodel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='currency',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='currency',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
